# https://github.com/jalallll
from PyQt5 import QtCore, QtGui, QtWidgets
from soup import confirmed, fatalities, recovered


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(624, 497)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color:rgb(0, 0, 0)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(250, 50, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("color:rgb(255, 255, 255)")
        self.title.setObjectName("title")
        self.flag = QtWidgets.QLabel(self.centralwidget)
        self.flag.setGeometry(QtCore.QRect(150, 30, 81, 71))
        self.flag.setText("")
        self.flag.setPixmap(QtGui.QPixmap(":/flag/flag.png"))
        self.flag.setScaledContents(True)
        self.flag.setWordWrap(False)
        self.flag.setObjectName("flag")
        self.confirmed = QtWidgets.QLabel(self.centralwidget)
        self.confirmed.setGeometry(QtCore.QRect(230, 140, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.confirmed.setFont(font)
        self.confirmed.setStyleSheet("color:rgb(255, 255, 255)")
        self.confirmed.setObjectName("confirmed")
        self.fatal = QtWidgets.QLabel(self.centralwidget)
        self.fatal.setGeometry(QtCore.QRect(230, 220, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.fatal.setFont(font)
        self.fatal.setStyleSheet("color:rgb(255, 255, 255)")
        self.fatal.setObjectName("fatal")
        self.recover = QtWidgets.QLabel(self.centralwidget)
        self.recover.setGeometry(QtCore.QRect(230, 310, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.recover.setFont(font)
        self.recover.setStyleSheet("color:rgb(255, 255, 255)")
        self.recover.setObjectName("recover")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(90, 140, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color:rgb(255, 255, 255)")
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(90, 220, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(80, 310, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setStyleSheet("color:rgb(255, 255, 255)")
        self.label3.setObjectName("label3")
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setGeometry(QtCore.QRect(520, 50, 71, 51))
        self.refreshButton.setStyleSheet("color: red")
        self.refreshButton.setObjectName("refreshButton")
        ##
        # if self.refreshButton.clicked():
        #     self.refreshButton.clicked.connect(lambda : confirmed())
        #     self.refreshButton.clicked.connect(lambda: fatalities())
        #     self.refreshButton.clicked.connect(lambda: recovered())
        ##
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 624, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # If refresh button clicked, execute clicked()
        self.refreshButton.pressed.connect(lambda: self.clicked())

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Covid19 Tracker"))
        self.confirmed.setText(_translate("MainWindow", "##"))
        self.fatal.setText(_translate("MainWindow", "##"))
        self.recover.setText(_translate("MainWindow", "##"))
        self.label1.setText(_translate("MainWindow", "Confirmed"))
        self.label2.setText(_translate("MainWindow", "Fatalities"))
        self.label3.setText(_translate("MainWindow", "Recoveries"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))

    # Update labels
    def clicked(self):
        self.confirmed.setText(str(confirmed()))
        self.fatal.setText(str(fatalities()))
        self.recover.setText(str(recovered()))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
